'use strict';
const path=require('node:path');require('dotenv').config({path:path.join(__dirname,'..','.env')});
const express=require('express');const cors=require('cors');const {createPool}=require('./db');
const {assertAuthConfiguration,authenticate}=require('./governance/auth');const {createGovernanceRouter}=require('./governance/routes');const {CompanionError}=require('./governance/homeCompanionDomain');
const {createAuthRouter}=require('./governance/authRoutes');
function assertConfiguration(env=process.env){assertAuthConfiguration(env);if(!env.CLIENT_URL)throw new Error('CLIENT_URL is required');}
function createApp({pool,env=process.env}){assertConfiguration(env);const app=express();app.disable('x-powered-by');app.use(cors({origin:env.CLIENT_URL,credentials:true,methods:['GET','POST']}));app.use(express.json({limit:'1mb'}));app.get('/healthz',async(_req,res,next)=>{try{await pool.query('SELECT 1');res.json({status:'ok'});}catch(error){next(error);}});app.use('/api/auth',createAuthRouter(pool,env));app.use('/api/governance',authenticate(pool,env),createGovernanceRouter(pool));app.use((_req,res)=>res.status(404).json({error:'not_found'}));app.use((error,_req,res,_next)=>{if(error instanceof CompanionError){const status=error.code.endsWith('_not_found')?404:error.code.includes('blocked')?409:422;return res.status(status).json({error:error.code,message:error.message,details:error.details});}console.error({name:error.name,message:error.message});return res.status(500).json({error:'internal_error'});});return app;}
async function main(){assertConfiguration(process.env);const pool=createPool(process.env);const server=createApp({pool,env:process.env}).listen(Number(process.env.BACKEND_PORT||3001),process.env.BIND_HOST||'127.0.0.1');const shutdown=()=>server.close(async()=>{await pool.end();process.exit(0);});process.once('SIGINT',shutdown);process.once('SIGTERM',shutdown);}
if(require.main===module)main().catch(error=>{console.error(error.message);process.exit(1);});module.exports={assertConfiguration,createApp};
