'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {assessServiceCancellation,assertSubject,authorizeAction,authorizeConnector,buildRecommendation,createPreferenceVersion,deletionPlan,evaluateRecommendations,transitionFollowThrough}=require('../homeCompanionDomain');

test('explicit preferences are versioned, editable, age/accessibility-aware, and digest bound',()=>{const result=createPreferenceVersion({id:'p2',tenantId:'home-a',profileId:'profile-a',sequence:2,parentVersionId:'p1',explicitPreferences:[{key:'meal.spicy',value:'avoid'}],accessibility:{screenReader:true},ageBand:'adult',spendingLimitMinorUnits:2500});assert.equal(result.parentVersionId,'p1');assert.equal(result.preferences[0].source,'explicit');assert.match(result.preferenceDigest,/^[a-f0-9]{64}$/);});
test('invalid or inferred-looking preferences cannot enter the explicit preference record',()=>{assert.throws(()=>createPreferenceVersion({tenantId:'h',profileId:'p',explicitPreferences:[{key:'x',value:'probably'}]}),error=>error.code==='preference_invalid');});
test('connectors require consent, least privilege, expiry, and guardian approval for children',()=>{const grant=authorizeConnector({kind:'calendar',requestedScopes:['events.read'],allowedScopes:['events.read'],consentReceipt:'consent-1',consentStatus:'granted',expiresAt:'2026-12-01',profileAgeBand:'adult'});assert.deepEqual(grant.scopes,['events.read']);assert.equal(grant.deletionPropagationRequired,true);assert.throws(()=>authorizeConnector({kind:'commerce',requestedScopes:['orders.read','orders.write'],allowedScopes:['orders.read'],consentReceipt:'c',consentStatus:'granted',expiresAt:'x'}),error=>error.code==='scope_excessive');assert.throws(()=>authorizeConnector({kind:'content',requestedScopes:['history.read'],allowedScopes:['history.read'],consentReceipt:'c',consentStatus:'granted',expiresAt:'x',profileAgeBand:'child'}),error=>error.code==='guardian_approval_required');});
test('recommendations rank relevance and novelty while blocking safety, accessibility, age, and category violations',()=>{const result=buildRecommendation({tenantId:'h',profileId:'p',preferenceVersionId:'v1',preferenceDigest:'d1',ageBand:'child',allowedCategories:['activity'],blockedSafetyTags:['open-flame'],supportedAccessibility:['captions'],options:[{id:'safe',category:'activity',relevance:0.8,novelty:0.5,ageAppropriate:true,accessibility:['captions'],reasons:['explicit preference']},{id:'unsafe',category:'activity',relevance:1,novelty:1,ageAppropriate:false,safetyTags:['open-flame']}],dataSources:['explicit-preference-v1']});assert.equal(result.selectedOption.id,'safe');assert.equal(result.rejected[0].id,'unsafe');assert.equal(result.consequentialActionAllowed,false);assert.ok(result.explanation.factors.length);});
test('no recommendation is returned when every option violates policy',()=>{assert.throws(()=>buildRecommendation({tenantId:'h',profileId:'p',preferenceVersionId:'v',preferenceDigest:'d',allowedCategories:[],options:[{category:'x'}]}),error=>error.code==='no_safe_recommendation');});
test('representative evaluation covers relevance diversity safety accessibility cold start drift and failure fallback',()=>{const result=evaluateRecommendations({results:[{relevance:.9,diversity:.8,safetyViolation:0,accessibilityPass:1,coldStartRelevance:.7,preferenceDriftRecovery:.8,fallbackSuccess:1}],thresholds:{minimumRelevance:.8,minimumDiversity:.7,maximumSafetyViolationRate:0,minimumAccessibilityPassRate:1,minimumColdStartRelevance:.6,minimumPreferenceDriftRecovery:.7,minimumFallbackSuccessRate:1}});assert.equal(result.passed,true);const failing=evaluateRecommendations({results:[{}],thresholds:{minimumRelevance:1,minimumDiversity:1,maximumSafetyViolationRate:0,minimumAccessibilityPassRate:1,minimumColdStartRelevance:1,minimumPreferenceDriftRecovery:1,minimumFallbackSuccessRate:1}});assert.equal(failing.failures.length,6);});
function service(overrides={}){return {provider:'streamco',accountReference:'opaque-42',amountMinorUnits:2000,billingCycle:'monthly',priceEvidenceReceipt:'price-1',termsEvidenceReceipt:'terms-1',evidenceObservedAt:'2026-07-18T12:00:00Z',remainingCommitmentMonths:0,terminationFeeMinorUnits:0,essential:false,householdDependencies:0,accessibilityDependency:false,cancellationMethod:'provider portal',noticePeriodDays:1,...overrides};}
test('service cancellation optimizer uses current price and terms evidence with integer costs and remains advisory',()=>{const result=assessServiceCancellation({service:service(),evaluatedAt:'2026-07-18T13:00:00Z',maximumEvidenceAgeMs:7200000,horizonMonths:12,alternativeMonthlyMinorUnits:500});assert.equal(result.grossSavingsMinorUnits,24000);assert.equal(result.netSavingsMinorUnits,18000);assert.equal(result.eligible,true);assert.equal(result.cancellationAllowed,false);});
test('service cancellation blocks stale, essential, shared, accessibility-dependent, incomplete, or uneconomic actions',()=>{assert.throws(()=>assessServiceCancellation({service:service(),evaluatedAt:'2026-07-20T13:00:00Z'}),error=>error.code==='service_evidence_stale');const result=assessServiceCancellation({service:service({essential:true,householdDependencies:2,accessibilityDependency:true,cancellationMethod:null,terminationFeeMinorUnits:30000,remainingCommitmentMonths:1}),evaluatedAt:'2026-07-18T13:00:00Z',maximumEvidenceAgeMs:7200000,horizonMonths:12});assert.equal(result.eligible,false);assert.ok(result.blockers.length>=4);});
test('consequential action requires exact approval, actor, budget, age, active grant, and exact scope',()=>{const input={tenantId:'h',recommendationId:'r',recommendationDigest:'rd',recommendationStatus:'saved',approval:{actorId:'u',role:'guardian',decision:'approved',recommendationDigest:'rd'},actorId:'u',costMinorUnits:1000,spendingLimitMinorUnits:2000,profileAgeBand:'child',connectorScopes:['service.cancel'],connectorStatus:'active',requiredScope:'service.cancel'};assert.equal(authorizeAction(input).authorized,true);assert.throws(()=>authorizeAction({...input,costMinorUnits:3000,connectorScopes:[]}),error=>error.code==='action_blocked'&&error.details.blockers.includes('spending_limit'));});
test('follow-through needs typed failure/completion evidence and subject scope fails closed',()=>{assert.equal(transitionFollowThrough({status:'proposed'},'saved').status,'saved');assert.throws(()=>transitionFollowThrough({status:'in_progress'},'completed',{}),error=>error.code==='completion_evidence_required');assert.throws(()=>assertSubject({tenantId:'h',profileId:'p1',role:'member'},{tenantId:'h',profileId:'p2'}),error=>error.code==='profile_scope_violation');});
test('deletion plans propagate to every active connector and respect legal holds',()=>{const result=deletionPlan({profileId:'p',legalHold:true,activeConnectors:[{id:'g1',provider:'calendar',deletionDeadlineAt:'2026-08-01'}]});assert.equal(result.status,'propagating');assert.equal(result.hardDeleteAllowed,false);assert.equal(result.propagations[0].connectorId,'g1');});
